-- Script de criação dos Tabelas e Comentários do Sistema Visao
-- Autor: Alexandre e Rogerio
-- Favor informar antes de executar o script o schema que será usado para receber os objeetos

/************************************
*  INPUT PARAMETERS
************************************/
DEFINE owner=DB_EXCHANGE_VISAO_TST
DEFINE tabspace=DB_EXCHANGE_VISAO_TST


alter session set current_schema=&owner;

spool create_tables_visao.log

prompt "Creating Tables"

CREATE TABLE "TB_MOTIVO_RECUSA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NM_MOTIVO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DS_MOTIVO" VARCHAR2(255 BYTE), 
	"PID_TIPO_MOTIVO_RECUSA" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_INVESTIMENTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(45 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_FUNCIONALIDADE" 
   (	"ID" NUMBER, 
	"NM_MODULO" VARCHAR2(100 BYTE), 
	"NM_FUNCIONALIDADE" VARCHAR2(100 BYTE), 
	"NM_OPERACAO" VARCHAR2(100 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PERFIL" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"NM_PERFIL" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_USUARIO_DIGITADOR" 
   (	"ID" NUMBER, 
	"PID_USUARIO_DIGITADOR" NUMBER NOT NULL ENABLE, 
	"PID_USUARIO_CORRETOR" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_RESPONSAVEL_FINANCEIRO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"NUM_CPF" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"PID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"DT_NASCIMENTO" DATE NOT NULL ENABLE, 
	"DS_EMAIL" VARCHAR2(240 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_RESPONSAVEL_LEGAL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NUM_DOC_IDENTIFICACAO" VARCHAR2(20 BYTE), 
	"PID_DOCUMENTO_CIVIL" NUMBER, 
	"DS_EMAIL" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"PID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"NM_RESP_LEGAL" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"NUM_CPF" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"DT_NASCIMENTO" DATE, 
	"NM_ARQUIVO" VARCHAR2(200 BYTE), 
	"NUM_DDD_CELULAR" NUMBER(*,0), 
	"NUM_TEL_CELULAR" NUMBER(*,0)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PARAMETRIZACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DURACAO_HRS" NUMBER NOT NULL ENABLE, 
	"DT_INCLUSAO" TIMESTAMP (6) NOT NULL ENABLE, 
	"CD_RESP_INCLUSAO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CD_RESP_ATUAL" VARCHAR2(20 BYTE), 
	"DT_RESP_ATUAL" TIMESTAMP (6), 
	"TP_PARAMETRO" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ENDERECO" 
   (	"ID" NUMBER, 
	"PID_TIPO_ENDERECO" NUMBER NOT NULL ENABLE, 
	"DS_ENDERECO" VARCHAR2(100 CHAR), 
	"DS_COMPLEMENTO" VARCHAR2(100 CHAR), 
	"DS_BAIRRO" VARCHAR2(100 CHAR), 
	"NU_CEP" NUMBER(8,0), 
	"PID_UF" NUMBER NOT NULL ENABLE, 
	"NM_CIDADE" VARCHAR2(100 CHAR), 
	"NU_ENDERECO" VARCHAR2(6 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PRODUTO_EMPRESA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_PRODUTO" NUMBER NOT NULL ENABLE, 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_COMISSAO" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"CD_PROCESSO" NUMBER, 
	"NM_SEGURADO" VARCHAR2(200 BYTE), 
	"CD_MATRICULA" NUMBER, 
	"CD_PROPOSTA" NUMBER, 
	"NM_CONTRATO" VARCHAR2(100 BYTE), 
	"CD_PARCELA" NUMBER, 
	"DT_VENCIMENTO" DATE, 
	"NM_PRODUTO" VARCHAR2(100 BYTE), 
	"VL_BASE" NUMBER(15,2), 
	"PERCENTUAL" NUMBER(5,2), 
	"VL_COMISSAO" NUMBER(5,2), 
	"CD_EVENTO" NUMBER, 
	"NM_EVENTO" VARCHAR2(100 BYTE), 
	"REGISTRO_ESTORNO" VARCHAR2(100 BYTE), 
	"DT_PAGAMENTO" DATE, 
	"VL_APLICADO_EVENTO" NUMBER(5,2), 
	"VL_ESTORNO_TOTAL" NUMBER(5,2), 
	"CD_PONTO_VENDA" NUMBER, 
	"NM_PONTO_VENDA" VARCHAR2(100 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_COMPRA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"UUID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"DT_COMPRA" TIMESTAMP (6) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQ_ALIQ" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NU_PROPOSTA" NUMBER, 
	"VL_SALDO" NUMBER(18,2), 
	"PID_ARQ_STATUS_CARGA" NUMBER(10,0) NOT NULL ENABLE, 
	"NU_CONTRATO" NUMBER(12,0), 
	"NU_MATRICULA" NUMBER(8,0), 
	"NM_CLIENTE" VARCHAR2(60 BYTE), 
	"NU_CPF" VARCHAR2(14 BYTE), 
	"TP_PARTICIPANTE" VARCHAR2(1 BYTE), 
	"NU_CERTIFICADO" NUMBER(12,0), 
	"DT_IMPLANTACAO" DATE, 
	"NU_COTAS" NUMBER(18,8), 
	"DT_SALDO_RESERVA" DATE, 
	"DS_STATUS_COBRANCA" VARCHAR2(30 BYTE), 
	"DS_STATUS_CERTIFICADO" VARCHAR2(200 BYTE), 
	"DS_TIPO_PLANO" VARCHAR2(20 BYTE), 
	"DS_REGIME_TRIBUTARIO" VARCHAR2(50 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_HISTORICO_DOCUMENTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_DOCUMENTO" NUMBER NOT NULL ENABLE, 
	"PID_SITUACAO" NUMBER NOT NULL ENABLE, 
	"DT_ATUALIZACAO" TIMESTAMP (6) NOT NULL ENABLE, 
	"IP" VARCHAR2(50 BYTE), 
	"UA" VARCHAR2(500 BYTE), 
	"NM_USUARIO" VARCHAR2(200 BYTE), 
	"PID_MOTIVO_RECUSA" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_PARAMETRO" 
   (	"ID" NUMBER, 
	"DS_TIPO_PARAMETRO" VARCHAR2(20 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_RAMO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CD_RAMO" NUMBER(2,0) NOT NULL ENABLE, 
	"NM_RAMO" VARCHAR2(500 CHAR) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_COMP_ALIQ" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_ALIQ" NUMBER NOT NULL ENABLE, 
	"PC_ALIQ" NUMBER(4,2), 
	"VL_SALDO" NUMBER(18,2), 
	"VL_BASE_CALCULO" NUMBER(18,2)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQ_PORTABILIDADE_INTERNA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_STATUS" NUMBER NOT NULL ENABLE, 
	"NM_CORRETOR" VARCHAR2(100 BYTE), 
	"NM_PRODUTO" VARCHAR2(100 BYTE), 
	"NM_FUNDO" VARCHAR2(100 BYTE), 
	"TP_FUNDO" VARCHAR2(20 BYTE), 
	"NM_BENEFICIO" VARCHAR2(100 BYTE), 
	"COMPETENCIA" VARCHAR2(100 BYTE), 
	"MOVIMENTO" VARCHAR2(20 BYTE), 
	"VL_MOVIMENTO" VARCHAR2(20 BYTE), 
	"QTD_MOVIMENTO" VARCHAR2(20 BYTE), 
	"CERTIFICADO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NM_CLIENTE" VARCHAR2(100 BYTE), 
	"DS_CPF" VARCHAR2(20 BYTE), 
	"CONTRATO" VARCHAR2(20 BYTE), 
	"AGENCIA" VARCHAR2(20 BYTE), 
	"NOME_AGENCIA" VARCHAR2(100 BYTE), 
	"FILIAL" VARCHAR2(20 BYTE), 
	"NOME_FILIAL" VARCHAR2(100 BYTE), 
	"CD_CLIENTE" VARCHAR2(20 BYTE), 
	"CD_FUNDO" VARCHAR2(20 BYTE), 
	"UF" VARCHAR2(20 BYTE), 
	"CD_PARCEIRO" VARCHAR2(20 BYTE), 
	"CD_MUMPS" VARCHAR2(20 BYTE), 
	"CD_I4PRO" VARCHAR2(20 BYTE), 
	"CD_PRODUTO" VARCHAR2(20 BYTE), 
	"DT_MOVIMENTACAO" VARCHAR2(20 BYTE), 
	"DT_COTA" VARCHAR2(20 BYTE), 
	"FUNCIONARIO" VARCHAR2(20 BYTE), 
	"FORMA_CONTRIBUICAO" VARCHAR2(20 BYTE), 
	"REGIME_TRIBUTACAO" VARCHAR2(20 BYTE), 
	"DS_CERTIFICADO_ORIGEM" VARCHAR2(20 BYTE), 
	"DS_CERTIFICADO_DESTINO" VARCHAR2(20 BYTE), 
	"PROPOSTA" VARCHAR2(20 BYTE), 
	"FORMA_PGTO" VARCHAR2(20 BYTE), 
	"CD_PLANO_ORIGEM" VARCHAR2(20 BYTE), 
	"CD_PLANO_DESTINO" VARCHAR2(20 BYTE), 
	"NU_LINHA" VARCHAR2(20 BYTE), 
	"CD_PORTABILIDADE" VARCHAR2(20 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_DOCUMENTO_BENEFICIARIO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PC_PARTICIPACAO" NUMBER(5,2), 
	"PID_DOCUMENTO_PREVIDENCIA" NUMBER NOT NULL ENABLE, 
	"DT_NASCIMENTO" DATE, 
	"NM_BENEFICIARIO" VARCHAR2(250 BYTE), 
	"PID_GRAU_PARENTESCO" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_CODIGO_ACESSO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CD_TRANSACAO" NUMBER(6,0) NOT NULL ENABLE, 
	"DT_CRIACAO" TIMESTAMP (6) NOT NULL ENABLE, 
	"PID_COMPRA" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_INVESTIMENTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NM_INVESTIMENTO" VARCHAR2(100 BYTE), 
	"VL_APORTE" NUMBER(18,2), 
	"VL_CONTRIBUICAO" NUMBER(18,2), 
	"COR" VARCHAR2(80 BYTE), 
	"PID_TIPO_INVESTIMENTO" NUMBER NOT NULL ENABLE, 
	"PID_RISCO_PRE_FORMAT" NUMBER, 
	"DS_RESUMO" VARCHAR2(400 BYTE), 
	"FL_MAIOR_VENDA" CHAR(1 BYTE), 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"CD_FUNDO_SEG" VARCHAR2(20 BYTE), 
	"FL_APORTE_OBRIG" CHAR(1 BYTE), 
	"FL_CONTRIB_OBRIG" CHAR(1 BYTE), 
	"PID_PRODUTO" NUMBER, 
	"FL_VISAO_CLIENTE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FL_ATIVO" CHAR(1 BYTE) NOT NULL ENABLE, 
	"PID_TIPO_RISCO" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_SEXO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_SEXO" VARCHAR2(20 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PAIS" 
   (	"CD_PAIS" NUMBER NOT NULL ENABLE, 
	"NM_PAIS" VARCHAR2(200 BYTE), 
	"SG_PAIS" VARCHAR2(5 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PORTABILIDADE_STATUS" 
   (	"ID" NUMBER, 
	"DT_PROCESSAMENTO" DATE, 
	"PID_PORTABILIDADE" NUMBER, 
	"DT_MOVIMENTO" DATE, 
	"DS_ESTAGIO" VARCHAR2(200 BYTE), 
	"DS_STATUS" VARCHAR2(200 BYTE), 
	"DS_RESPONSAVEL" VARCHAR2(200 BYTE), 
	"DS_MOTIVO" VARCHAR2(200 BYTE), 
	"DS_OBSERVACAO" VARCHAR2(500 BYTE), 
	"DT_INCLUSAO" TIMESTAMP (6)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_DE_PARA_HISTORICO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_CODIGO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DS_DESCRICAO" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"FL_POSITIVO" VARCHAR2(1 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_RISCO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_TIPO_RISCO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FL_ATIVO" VARCHAR2(1 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_VISAO" 
   (	"ID" NUMBER, 
	"NM_VISAO" VARCHAR2(150 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_DOCUMENTO_PREVIDENCIA" 
   (	"PID_DOCUMENTO_PREVIDENCIA" NUMBER(19,0) NOT NULL ENABLE, 
	"NUM_APOLICE" NUMBER(19,0), 
	"NUM_IDADE_CONCESSAO" NUMBER(19,0) NOT NULL ENABLE, 
	"VL_APORTE_INICIAL" FLOAT(126), 
	"VL_CONTRIBUICAO" NUMBER(18,2), 
	"PID_REGIME_TRIBUTARIO" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_USUARIO_CANAL_VENDA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_CANAL_VENDA" NUMBER NOT NULL ENABLE, 
	"PID_USUARIO" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_SEGURADORA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NM_SEGURADORA" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"NUM_CNPJ" VARCHAR2(14 BYTE) NOT NULL ENABLE, 
	"CD_FIP" NUMBER, 
	"FL_ATIVO" VARCHAR2(1 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_DOCUMENTO_CIVIL" 
   (	"CD_DOCUMENTO" NUMBER(5,0) NOT NULL ENABLE, 
	"DS_DOCUMENTO" VARCHAR2(50 BYTE), 
	"FL_ATIVO" VARCHAR2(1 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_USUARIO" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"LOGIN_USUARIO" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"DS_SENHA" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"FL_PRIMEIRO_ACESSO" VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL ENABLE, 
	"NU_ERROS_ACESSO" NUMBER(1,0), 
	"FL_BLOQUEADO" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"FL_ATIVO" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"DS_EMAIL" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"PID_PERFIL" NUMBER, 
	"NU_CPF_CNPJ" VARCHAR2(14 BYTE), 
	"DT_CADASTRO" DATE, 
	"NM_USUARIO" VARCHAR2(200 BYTE), 
	"PID_ESTRUTURA_VENDA" NUMBER, 
	"PID_GRUPO" NUMBER, 
	"PID_VISAO" NUMBER, 
	"FL_VISAO_LOGADA" CHAR(1 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_MOTIVO_RECUSA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_MOTIVO" VARCHAR2(100 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQUIVO_COTA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_STATUS" NUMBER NOT NULL ENABLE, 
	"TP_REGISTRO" VARCHAR2(1 BYTE), 
	"DT_INDICE" VARCHAR2(8 BYTE), 
	"CD_FUNDO" VARCHAR2(5 BYTE), 
	"VL_COTA" NUMBER, 
	"VL_SALDO" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_DOCUMENTO" 
   (	"ID_DOCUMENTO" NUMBER NOT NULL ENABLE, 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"PID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"PID_RAMO" NUMBER NOT NULL ENABLE, 
	"DT_CADASTRO" DATE NOT NULL ENABLE, 
	"PID_TIPO_DOCUMENTO" NUMBER NOT NULL ENABLE, 
	"NUM_DOC_SEG" NUMBER, 
	"PID_SITUACAO_SEGURADORA" NUMBER, 
	"PID_CANAL_VENDA" NUMBER, 
	"PID_USUARIO_DIGITADOR" NUMBER, 
	"PID_ESTRUTURA_VENDA" NUMBER, 
	"PID_COMPRA" NUMBER, 
	"PID_USUARIO" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PORTABILIDADE" 
   (	"PID_DOCUMENTO_PORTABILIDADE" NUMBER NOT NULL ENABLE, 
	"PID_SEGURADORA_CED" NUMBER NOT NULL ENABLE, 
	"PID_TIPO_PRODUTO" NUMBER NOT NULL ENABLE, 
	"PID_REGIME_TRIBUTARIO_CED" NUMBER NOT NULL ENABLE, 
	"PID_TIPO_ENTIDADE_CED" NUMBER, 
	"VL_PORTABILIDADE" NUMBER NOT NULL ENABLE, 
	"NM_PLANO_CED" VARCHAR2(100 BYTE), 
	"PID_TIPO_PORTABILIDADE" NUMBER NOT NULL ENABLE, 
	"NUM_CNPJ_FUNDO_CED" VARCHAR2(14 BYTE) DEFAULT (' ') NOT NULL ENABLE, 
	"NUM_CERTIFICADO_CED" VARCHAR2(50 BYTE), 
	"NUM_SUSEP_FUNDO_CED" VARCHAR2(20 BYTE), 
	"PID_DOCUMENTO_PREVIDENCIA" NUMBER NOT NULL ENABLE, 
	"NM_ARQUIVO" VARCHAR2(200 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_PORTABILIDADE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_TIPO_VALOR_PORTABILIDADE" VARCHAR2(50 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_ENTIDADE" 
   (	"CD_TIPO_ENTIDADE" NUMBER(3,0) NOT NULL ENABLE, 
	"DS_TIPO_ENTIDADE" VARCHAR2(50 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TITULARIDADE" 
   (	"CD_TITULARIDADE" NUMBER(22,3) NOT NULL ENABLE, 
	"DS_TITULARIDADE" VARCHAR2(100 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_SITUACAO_SEGURADORA" 
   (	"ID" NUMBER, 
	"DS_SITUACAO" VARCHAR2(60 BYTE), 
	"PID_TIPO_DOCUMENTO" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_BANCO" 
   (	"CD_BANCO" NUMBER(3,0) NOT NULL ENABLE, 
	"DESC_BANCO" VARCHAR2(100 BYTE), 
	"NUM_BANCO" NUMBER(3,0)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_ENDERECO" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"NM_TIPO_ENDERECO" VARCHAR2(100 CHAR) NOT NULL DISABLE, 
	"DS_TIPO_ENDERECO" VARCHAR2(100 CHAR)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_EMPRESA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_TIPO_EMPRESA" VARCHAR2(50 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_DOCUMENTO_COBRANCA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_DOCUMENTO_PREVIDENCIA" NUMBER NOT NULL ENABLE, 
	"PID_BANCO" NUMBER, 
	"NUM_AGENCIA" VARCHAR2(20 BYTE), 
	"DV_CONTA_CORRENTE" VARCHAR2(20 BYTE), 
	"PID_FORMA_PAGAMENTO" NUMBER NOT NULL ENABLE, 
	"NUM_CONTA_CORRENTE" VARCHAR2(20 BYTE), 
	"PID_DIA_VENCIMENTO" NUMBER, 
	"DV_AGENCIA" VARCHAR2(20 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQUIVO_PORTABILIDADE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_STATUS" NUMBER NOT NULL ENABLE, 
	"NM_CLIENTE" VARCHAR2(100 BYTE), 
	"DS_CPF" VARCHAR2(14 BYTE), 
	"DS_STATUS" VARCHAR2(25 BYTE), 
	"VL_VALOR" NUMBER, 
	"NM_CEDENTE" VARCHAR2(100 BYTE), 
	"DS_CERTIFICADO_ORIGEM" VARCHAR2(30 BYTE), 
	"DS_CERTIFICADO_DESTINO" VARCHAR2(30 BYTE), 
	"DS_OBSERVACAO" VARCHAR2(255 BYTE), 
	"DS_MOTIVO_RECUSA" VARCHAR2(255 BYTE), 
	"NU_LINHA" NUMBER NOT NULL ENABLE, 
	"DT_ENVIO_SID" DATE, 
	"DT_CONCLUSAO" DATE, 
	"CD_PORTABILIDADE" VARCHAR2(20 BYTE), 
	"TP_PLANO" VARCHAR2(50 BYTE), 
	"PID_MOTIVO_RECUSA" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_NIF" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NUM_NIF" VARCHAR2(20 BYTE), 
	"PID_PAIS" NUMBER NOT NULL ENABLE, 
	"PID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"PID_MOTIVO_NIF" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_EMPRESA_PARAMETRO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"FL_HABILITA_PORTABILIDADE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FL_HABILITA_BENEFICIARIO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FL_HABILITA_RESP_FINANCEIRO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"DS_DISCLAIMER_BANCO" VARCHAR2(1000 BYTE), 
	"DS_DISCLAIMER_PORT" VARCHAR2(1000 BYTE), 
	"NU_IDADE_MAX_APOSENT" NUMBER(3,0) NOT NULL ENABLE, 
	"FL_HABILITA_PGBL" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FL_HABILITA_VGBL" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FL_HABILITA_REGRESSIVA" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FL_HABILITA_PROGRESSIVA" VARCHAR2(1 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_OBSERVACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_OBSERVACAO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PID_INVESTIMENTO" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_HISTORICO_DOC_CORRETOR" 
   (	"ID" NUMBER, 
	"PID_DOCUMENTO" NUMBER, 
	"DT_ALTERACAO" DATE NOT NULL ENABLE, 
	"PID_USUARIO_ANTERIOR" NUMBER, 
	"PID_USUARIO_ATUAL" NUMBER, 
	"PID_CORRETOR_ANTERIOR" NUMBER, 
	"PID_CORRETOR_ATUAL" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_COBERTURA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_COBERTURA" VARCHAR2(100 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_GRUPO_FUNCIONALIDADE" 
   (	"ID" NUMBER, 
	"PID_GRUPO" NUMBER(5,0) NOT NULL ENABLE, 
	"PID_FUNCIONALIDADE" NUMBER(5,0) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQUIVO_CADA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_STATUS" NUMBER NOT NULL ENABLE, 
	"TP_ARQUIVO" VARCHAR2(1 BYTE), 
	"NU_PROPOSTA" NUMBER, 
	"NU_MATRICULA" NUMBER, 
	"NM_TITULAR" VARCHAR2(200 BYTE), 
	"DS_LOGRADOURO" VARCHAR2(100 BYTE), 
	"DS_BAIRRO" VARCHAR2(100 BYTE), 
	"DS_CIDADE" VARCHAR2(100 BYTE), 
	"DS_CEP" VARCHAR2(8 BYTE), 
	"DS_UF" VARCHAR2(2 BYTE), 
	"NU_TELEFONE1" NUMBER, 
	"NU_TELEFONE2" NUMBER, 
	"NM_FUNDO" VARCHAR2(200 BYTE), 
	"CD_FUNDO" VARCHAR2(20 BYTE), 
	"CT_FUNDO" VARCHAR2(20 BYTE), 
	"DT_SALDO" VARCHAR2(8 BYTE), 
	"QT_COTAS" NUMBER, 
	"VL_SALDO" NUMBER, 
	"DT_LIBERACAO_PORTABILIDADE" VARCHAR2(8 BYTE), 
	"DT_LIGERACAO_RESGATE" VARCHAR2(8 BYTE), 
	"DS_SITUACAO" VARCHAR2(100 BYTE), 
	"NU_LINHA" NUMBER NOT NULL ENABLE, 
	"NU_PROC_SUSEP" VARCHAR2(20 BYTE), 
	"NU_CPF" VARCHAR2(14 BYTE), 
	"TP_PARTICIPANTE" VARCHAR2(1 BYTE), 
	"NU_IDENTIDADE" VARCHAR2(20 BYTE), 
	"DS_NATUREZA_DOC" VARCHAR2(50 BYTE), 
	"DS_ORGAO_EMISSOR" VARCHAR2(80 BYTE), 
	"DT_EXPEDICAO" VARCHAR2(8 BYTE), 
	"TP_REGIME_IR" VARCHAR2(1 BYTE), 
	"DS_REGIME_IR" VARCHAR2(50 BYTE), 
	"DS_BANCO_PATROCINIO" VARCHAR2(100 BYTE), 
	"DS_AGENCIA_PATROCINIO" VARCHAR2(20 BYTE), 
	"DS_CONTA_PATROCINIO" VARCHAR2(20 BYTE), 
	"NU_CNPJ_PATROCINIO" VARCHAR2(14 BYTE), 
	"DS_BANCO_PARTICIPANTE" VARCHAR2(100 BYTE), 
	"DS_AGENCIA_PARTICIPANTE" VARCHAR2(20 BYTE), 
	"DS_CONTA_PARTICIPANTE" VARCHAR2(20 BYTE), 
	"VL_IOF" VARCHAR2(12 BYTE), 
	"VL_IR" VARCHAR2(12 BYTE), 
	"VL_SALDO_LIQUIDO" VARCHAR2(12 BYTE), 
	"DT_NASCIMENTO" VARCHAR2(8 BYTE), 
	"NU_CERTIFICADO" VARCHAR2(20 BYTE), 
	"NM_PLANO" VARCHAR2(100 BYTE), 
	"NU_CONTRATO" VARCHAR2(20 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_MOTIVO_NIF" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_MOTIVO" VARCHAR2(200 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_UF" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_UF" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"NM_UF" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PARAMETRO_FTP" 
   (	"ID" NUMBER, 
	"PID_SEGURADORA" NUMBER, 
	"NM_USUARIO" VARCHAR2(100 BYTE), 
	"DS_SENHA" VARCHAR2(100 BYTE), 
	"NM_HOST" VARCHAR2(255 BYTE), 
	"NU_PORTA" NUMBER, 
	"TP_CONEXAO" NUMBER(1,0)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_NUM_DOCUMENTO_SEG" 
   (	"NUM_DOCUMENTO_SEG" NUMBER NOT NULL ENABLE, 
	"FL_ASSINADA" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PROPOSTA_FUNDO_INVESTIMENTO" 
   (	"NUM_DOC_SEG" NUMBER NOT NULL ENABLE, 
	"PC_DISTRIBUICAO" NUMBER(3,0) NOT NULL ENABLE, 
	"PID_FUNDO_INVESTIMENTO" NUMBER NOT NULL ENABLE, 
	"PID_DOCUMENTO_PREVIDENCIA" NUMBER(19,0) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PARAMETRO_BATCH" 
   (	"ID" NUMBER, 
	"PID_SEGURADORA" NUMBER, 
	"TP_ARQUIVO" NUMBER, 
	"DS_FTP_DIRETORIO" VARCHAR2(255 BYTE), 
	"DS_FTP_DIR_BACKUP" VARCHAR2(255 BYTE), 
	"DS_ARQUIVO_NOME" VARCHAR2(255 BYTE), 
	"DS_ARQUIVO_EXTENSAO" VARCHAR2(255 BYTE), 
	"DS_LOCAL_DIRETORIO" VARCHAR2(255 BYTE), 
	"PID_PARAMETRO_FTP" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_RISCO_PREFORMAT_COB" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_COBERTURA" NUMBER NOT NULL ENABLE, 
	"PID_RISCO_PRE_FORMATADO" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_GRUPO" 
   (	"ID" NUMBER, 
	"NM_GRUPO" VARCHAR2(100 BYTE), 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"FL_ATIVO" CHAR(1 BYTE) DEFAULT 1, 
	"DT_CADASTRO" DATE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_GRAU_PARENTESCO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DS_GRAU_PARENTESCO" VARCHAR2(50 BYTE), 
	"FL_ATIVO" CHAR(1 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_REGIME_TRIBUTARIO" 
   (	"ID" NUMBER(3,0) NOT NULL ENABLE, 
	"DS_REGIME_TRIBUTARIO" VARCHAR2(50 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_PRODUTO" 
   (	"CD_TIPO_PRODUTO" NUMBER NOT NULL ENABLE, 
	"DS_TIPO_PRODUTO" VARCHAR2(150 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQ_STATUS_CARGA_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_STATUS_CARGA" NUMBER NOT NULL ENABLE, 
	"NU_LINHA" NUMBER, 
	"NM_COLUNA" VARCHAR2(100 BYTE), 
	"DS_ERRO" VARCHAR2(255 BYTE), 
	"NR_DOCUMENTO" VARCHAR2(40 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQ_STATUS_CARGA" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DS_STATUS" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DT_CARGA" TIMESTAMP (6) NOT NULL ENABLE, 
	"NM_ARQUIVO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"TP_ARQUIVO" NUMBER NOT NULL ENABLE, 
	"VL_LINHA_INICIAL" NUMBER, 
	"PID_EMPRESA" NUMBER, 
	"PID_USUARIO" NUMBER, 
	"PID_SEGURADORA" NUMBER, 
	"DT_ARQUIVO" DATE, 
	"DS_POSICAO_DIARIA" VARCHAR2(20 BYTE), 
	"DS_INFORMATIVO" VARCHAR2(20 BYTE), 
	"CD_PARCERIA" VARCHAR2(4 BYTE), 
	"CD_BANCO" VARCHAR2(3 BYTE), 
	"DS_SEQUENCIAL" VARCHAR2(20 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_EMPRESA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NM_EMPRESA" VARCHAR2(100 CHAR), 
	"DS_EMAIL" VARCHAR2(240 BYTE), 
	"FL_LICENSA_ATIVA" VARCHAR2(1 CHAR) DEFAULT 'S', 
	"NU_SUSEP" VARCHAR2(20 CHAR), 
	"DS_CAMINHO_LOGOTIPO" VARCHAR2(255 BYTE), 
	"NU_MUMPS" VARCHAR2(20 BYTE), 
	"NUM_CNPJ" VARCHAR2(14 BYTE), 
	"DG" NUMBER, 
	"CD_PARCERIA" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"NM_EMPRESA_FANTASIA" VARCHAR2(100 BYTE), 
	"NUM_TELEFONE" VARCHAR2(50 BYTE), 
	"NM_APELIDO" VARCHAR2(20 BYTE), 
	"SENHA" VARCHAR2(50 CHAR), 
	"LOGIN" VARCHAR2(50 CHAR), 
	"CD_XPORT" NUMBER, 
	"NUM_FUNCAO" NUMBER, 
	"USAR_SERVICO_ATIVO" VARCHAR2(1 BYTE), 
	"PID_EMPRESA_SECUNDARIA" NUMBER, 
	"PID_EMPRESA_SUPERIOR" NUMBER, 
	"PID_TIPO_EMPRESA" NUMBER, 
	"PID_USUARIO_B2C" NUMBER
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_DOCUMENTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NM_TIPO_DOCUMENTO" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_SITUACAO" 
   (	"ID" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"DS_SITUACAO" VARCHAR2(60 BYTE) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_DIA_VENCIMENTO" 
   (	"ID_DIA_VENCIMENTO" NUMBER(2,0) NOT NULL ENABLE, 
	"NUM_DIA_VENCIMENTO" NUMBER(2,0)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQUIVO_MOVI" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_STATUS" NUMBER NOT NULL ENABLE, 
	"TP_REGISTRO" NUMBER(1,0), 
	"DS_HISTORICO" VARCHAR2(40 BYTE), 
	"NU_PROPOSTA" NUMBER, 
	"NU_MATRICULA" NUMBER, 
	"NU_CERTIFICADO" NUMBER, 
	"NM_FUNDO" VARCHAR2(60 BYTE), 
	"CD_FUNDO" VARCHAR2(6 BYTE), 
	"CT_FUNDO" VARCHAR2(9 BYTE), 
	"DT_MOVIMENTO" VARCHAR2(8 BYTE), 
	"QT_COTAS" NUMBER, 
	"VL_MOVIMENTO" NUMBER, 
	"DT_COTA" VARCHAR2(8 BYTE), 
	"VL_COTA" NUMBER, 
	"VL_DA" NUMBER, 
	"VL_IR" NUMBER, 
	"NU_DOCUMENTO" NUMBER, 
	"DT_PAGAMENTO" VARCHAR2(8 BYTE), 
	"NU_PARCELA" NUMBER, 
	"VALOR_TAXA_SAIDA" NUMBER, 
	"DS_OPERACAO_REALIZADA" VARCHAR2(30 BYTE), 
	"CD_ANGARIADOR" VARCHAR2(14 BYTE), 
	"DS_AGENCIA" VARCHAR2(8 BYTE), 
	"VL_IDENTIFICACAO_CLIENTE" VARCHAR2(20 BYTE), 
	"NM_PRODUTO" VARCHAR2(30 BYTE), 
	"CD_PLANO_PARCEIRO" VARCHAR2(10 BYTE), 
	"NU_PROTOCOLO" NUMBER, 
	"VL_NOMINAL" NUMBER, 
	"DS_CGC_CPF_CLIENTE" VARCHAR2(14 BYTE), 
	"CD_MOVIMENTO_ICATU" VARCHAR2(9 BYTE), 
	"DT_SOLICITACAO" VARCHAR2(8 BYTE), 
	"NU_PROC_SUSEP" VARCHAR2(20 BYTE), 
	"DS_SINAL_MOVIMENTACAO" VARCHAR2(1 BYTE), 
	"NU_CONTRATO" VARCHAR2(15 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_CLIENTE" 
   (	"ID" NUMBER, 
	"NUM_DOC_IDENTIFICACAO" VARCHAR2(20 BYTE), 
	"DT_NASCIMENTO" DATE, 
	"PID_ESTADO_CIVIL" NUMBER NOT NULL ENABLE, 
	"NUM_CPF" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"PID_TITULARIDADE" NUMBER NOT NULL ENABLE, 
	"PID_DOCUMENTO_CIVIL" NUMBER NOT NULL ENABLE, 
	"PID_ORGAO_EMISSOR" NUMBER NOT NULL ENABLE, 
	"DT_EXPEDICAO" DATE, 
	"PID_OCUPACAO" NUMBER NOT NULL ENABLE, 
	"FL_PPE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"DS_ORIGEM_RECURSO" VARCHAR2(20 BYTE), 
	"VL_RENDA_PATRIMONIO" NUMBER(13,2) NOT NULL ENABLE, 
	"PID_PAIS_NACIONALIDADE" NUMBER NOT NULL ENABLE, 
	"PID_PAIS_OUTRA_NACIONALIDADE" NUMBER, 
	"FL_ESTEVE_EUA" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"NUM_DDD_RESIDENCIAL" NUMBER, 
	"NUM_TELEFONE_RESIDENCIAL" NUMBER, 
	"DS_EMAIL" VARCHAR2(240 BYTE), 
	"NM_CLIENTE" VARCHAR2(250 BYTE), 
	"PID_ENDERECO" NUMBER NOT NULL ENABLE, 
	"PID_SEXO" NUMBER NOT NULL ENABLE, 
	"NUM_DDD_CELULAR" NUMBER, 
	"NUM_TELEFONE_CELULAR" NUMBER, 
	"PID_PAIS_ENDERECO_POSTAL" NUMBER, 
	"DS_EMPRESA" VARCHAR2(80 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQUIVO_PLAN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_STATUS" NUMBER NOT NULL ENABLE, 
	"TP_REGISTRO" VARCHAR2(1 BYTE), 
	"NM_FUNDO" VARCHAR2(100 BYTE), 
	"CD_FUNDO" VARCHAR2(20 BYTE), 
	"VL_DA" NUMBER, 
	"NUM_PROC_SUSEP" VARCHAR2(20 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ESTRUTURA_VENDA" 
   (	"ID" NUMBER, 
	"NM_ESTRUTURA_VENDA" VARCHAR2(100 BYTE), 
	"NUM_CNPJ_CPF" VARCHAR2(14 BYTE), 
	"PID_UF" NUMBER, 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"DT_CADASTRO" DATE, 
	"FL_ATIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"PID_ESTRUTURA_VENDA_SUPERIOR" NUMBER, 
	"FL_PONTO_VENDA" VARCHAR2(1 BYTE) DEFAULT 'S'
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_CANAL_VENDA" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"NM_CANAL_VENDA" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"FL_ATIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"DT_CADASTRO" DATE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_FUNDO_INVESTIMENTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_INVESTIMENTO" NUMBER NOT NULL ENABLE, 
	"PID_FUNDO" NUMBER, 
	"PC_DISTRIBUICAO" NUMBER(3,0), 
	"NU_PROCESSO_SUSEP" VARCHAR2(20 BYTE), 
	"NM_PLANO" VARCHAR2(100 BYTE), 
	"CD_TP_CARREGAMENTO" NUMBER, 
	"POSSUI_PERFORMANCE" CHAR(1 BYTE), 
	"CD_FUNDO_SEG" VARCHAR2(20 BYTE), 
	"NU_CNPJ" VARCHAR2(15 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ARQUIVO_PAGAMENTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_ARQ_STATUS" NUMBER NOT NULL ENABLE, 
	"NU_LINHA" NUMBER NOT NULL ENABLE, 
	"NU_CERTIFICADO" VARCHAR2(20 BYTE), 
	"DT_CONTRIBUICAO" DATE, 
	"DT_COMPETENCIA" DATE, 
	"VL_PARCELA" NUMBER, 
	"NU_PARCELA" NUMBER, 
	"DS_FORMA_CONTRIBUICAO" VARCHAR2(50 BYTE), 
	"DS_STATUS" VARCHAR2(50 BYTE), 
	"DT_VENCIMENTO" DATE, 
	"TP_COBRANCA" VARCHAR2(50 BYTE), 
	"DS_RETORNO_BANCARIO" VARCHAR2(100 BYTE), 
	"DS_MOTIVO" VARCHAR2(100 BYTE), 
	"NM_CLIENTE" VARCHAR2(100 BYTE), 
	"NU_CPF_CNPJ" VARCHAR2(20 BYTE), 
	"NM_FUNDO" VARCHAR2(100 BYTE), 
	"VL_RESERVA" NUMBER, 
	"DS_CANAL_AFINIDADE" VARCHAR2(100 BYTE), 
	"NM_PLANO" VARCHAR2(100 BYTE), 
	"DS_PARCERIA" VARCHAR2(100 BYTE), 
	"CD_BANCO" VARCHAR2(10 BYTE), 
	"NU_AGENCIA" VARCHAR2(10 BYTE), 
	"NU_CONTA_CORRENTE" VARCHAR2(20 BYTE), 
	"NU_DIA_VENCIMENTO" VARCHAR2(10 BYTE), 
	"DS_HAVERA_REPIQUE" VARCHAR2(10 BYTE), 
	"NM_BANCO" VARCHAR2(50 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_FUNDO" 
   (	"NM_FUNDO" VARCHAR2(100 BYTE) NOT NULL DISABLE, 
	"ID" NUMBER NOT NULL DISABLE, 
	"VL_TAF" NUMBER(18,2), 
	"NU_CNPJ" VARCHAR2(15 BYTE) NOT NULL DISABLE, 
	"CD_FUNDO_SEG" VARCHAR2(20 BYTE), 
	"NM_FUNDO_REDUZIDO" VARCHAR2(40 BYTE) NOT NULL DISABLE, 
	"DSC_PERFORMANCE" VARCHAR2(500 BYTE), 
	"LOGO" VARCHAR2(20 BYTE), 
	"DS_FUNDO" VARCHAR2(4000 BYTE), 
	"DS_GESTOR" VARCHAR2(4000 BYTE), 
	"NM_GESTOR" VARCHAR2(4000 BYTE), 
	"VL_TAXA_ADM_MAXIMA" NUMBER(18,2), 
	"VL_TAXA_ADM_MINIMA" NUMBER(18,2), 
	"DSC_LMAX_TX_PERFORMANCE" VARCHAR2(500 BYTE), 
	"FL_PLANO_QUALIFICADO" VARCHAR2(1 BYTE), 
	"DS_TIPO_RENDA" VARCHAR2(500 BYTE), 
	"VL_CARENCIA_INICIAL_RESGATE" NUMBER, 
	"VL_CARENCIA_INI_PORT_EXT" NUMBER, 
	"VL_CARENCIA_INI_PORT_IN" NUMBER, 
	"VL_CARENCIA_ENTRE_RESGATE" NUMBER, 
	"VL_CARENCIA_ENTRE_PORT_EXT" NUMBER, 
	"VL_ATUALIZACAO_CONTRIBUICAO" VARCHAR2(500 BYTE), 
	"VL_ATUALIZACAO_BENEFICIO" VARCHAR2(500 BYTE), 
	"VL_CARREGAMENTO_ENTRADA" VARCHAR2(500 BYTE), 
	"VL_CARREGAMENTO_SAIDA" VARCHAR2(500 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ESTADO_CIVIL" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"NM_ESTADO_CIVIL" VARCHAR2(100 CHAR) NOT NULL DISABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_OCUPACAO" 
   (	"CD_OCUPACAO" NUMBER NOT NULL ENABLE, 
	"DS_OCUPACAO" VARCHAR2(100 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_ORGAO_EMISSOR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SL_ORGAO" VARCHAR2(10 BYTE), 
	"NM_ORGAO" VARCHAR2(80 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_FORMA_PAGAMENTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NM_FORMA_PAGAMENTO" VARCHAR2(100 CHAR)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_TIPO_MEIO_COMUNICACAO" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"NM_MEIO_COMUNICACAO" VARCHAR2(100 CHAR) NOT NULL DISABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_COMISSAO_LOG" 
   (	"ID" NUMBER NOT NULL DISABLE, 
	"DS_ERRO" VARCHAR2(200 BYTE) NOT NULL DISABLE, 
	"CD_SEGURADORA" NUMBER, 
	"CD_USUARIO" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"DT_ARQUIVO" DATE, 
	"NM_ARQUIVO" VARCHAR2(100 BYTE)
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_PROPOSTA_COBERTURA" 
   (	"PID_DOCUMENTO" NUMBER NOT NULL ENABLE, 
	"PID_COBERTURA" NUMBER NOT NULL ENABLE, 
	"PID_RISCO_PREFORMAT_COB" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_FORMA_PAGTO_EMPRESA" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PID_FORMA_PAGAMENTO" NUMBER NOT NULL ENABLE, 
	"PID_EMPRESA" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_RISCO_PRE_FORMATADO" 
   (	"ID" NUMBER NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace ;

CREATE TABLE "TB_LAYOUT_EMAIL" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DS_ASSUNTO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DS_LAYOUT_EMAIL" CLOB NOT NULL ENABLE, 
	"DS_TIPO_LAYOUT_EMAIL" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) 
  TABLESPACE &tabspace 
    LOB ("DS_LAYOUT_EMAIL") STORE AS SECUREFILE (
  TABLESPACE &tabspace ENABLE STORAGE IN ROW CHUNK 8192 RETENTION AUTO
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE TABLE "TB_PRODUTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID_RAMO" NUMBER NOT NULL ENABLE, 
	"NM_PRODUTO" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"PID_TIPO_PRODUTO" NUMBER NOT NULL ENABLE, 
	"CD_PRODUTO_SEG" NUMBER, 
	"ATIVO" VARCHAR2(1 BYTE), 
	"DSC_PRODUTO" CLOB
   ) 
  TABLESPACE &tabspace 
    LOB ("DSC_PRODUTO") STORE AS SECUREFILE (
  TABLESPACE &tabspace ENABLE STORAGE IN ROW CHUNK 8192 RETENTION AUTO
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  -- Comments

  prompt "Creating Comentários"

 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_SITUACAO"."ID" IS 'ID da situaÁ„o da seguradora.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_SITUACAO"."DS_SITUACAO" IS 'Nome da situaÁ„o.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_RAMO"."CD_RAMO" IS 'CÛdigo SUSEP do ramo.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_RAMO"."NM_RAMO" IS 'Nome SUSEP do ramo.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_TIPO_MEIO_COMUNICACAO"."ID" IS '- Retrofitted';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_TIPO_MEIO_COMUNICACAO"."NM_MEIO_COMUNICACAO" IS '- Retrofitted';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_UF"."ID" IS 'Identificador ˙nico de cada UF.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_UF"."DS_UF" IS 'Sigla da UF.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_UF"."NM_UF" IS 'Nome da UF.';
 COMMENT ON TABLE "DB_EXCHANGE_VISAO_TST"."TB_UF"  IS 'Lista das Unidades Federativas.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."NM_CLIENTE" IS 'Nome Cliente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."DS_CPF" IS 'CPF';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."DS_STATUS" IS 'Status';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."VL_VALOR" IS 'Valor';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."NM_CEDENTE" IS 'cedente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."DS_CERTIFICADO_ORIGEM" IS 'Certificado/Proposta de Origem (Cedente)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."DS_CERTIFICADO_DESTINO" IS 'Certificado/Proposta de Destino (Icatu)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."DS_OBSERVACAO" IS 'OBS';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."DS_MOTIVO_RECUSA" IS 'Motivo Recusa';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE"."NU_LINHA" IS 'PosiÁ„o da linha no excel.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."TP_REGISTRO" IS 'Tipo de Registro';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DS_HISTORICO" IS 'CÛdigo da operaÁ„o realizada';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NU_PROPOSTA" IS 'N˙mero da proposta do cliente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NU_MATRICULA" IS 'N˙mero da matrÌcula do cliente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NU_CERTIFICADO" IS 'N˙mero do certificado do cliente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NM_FUNDO" IS 'Nome do Fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."CD_FUNDO" IS 'CÛdigo do Fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."CT_FUNDO" IS 'CÛdigo de investimento do cliente no fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DT_MOVIMENTO" IS 'Data em que o movimento ocorreu (yyyymmdd)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."QT_COTAS" IS 'Quantidade de cotas referentes ao movimento ("000000000.00000000")';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."VL_MOVIMENTO" IS 'Valor do movimento ("00000000.00")';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DT_COTA" IS 'Data da cota';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."VL_COTA" IS 'Valor da cota ("000000000.00000000")';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."VL_DA" IS 'Valor da "DA" recolhida ("00000000.00")"';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."VL_IR" IS 'Valor do "IR" recolhido ("00000000.00")';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NU_DOCUMENTO" IS 'N˙mero do documento que identifica a operaÁ„o realizada ("000000000000")';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DT_PAGAMENTO" IS 'Data do Pagamento (yyyymmdd)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NU_PARCELA" IS 'Numero da quando pagamento de cobranÁa';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."VALOR_TAXA_SAIDA" IS 'Valor da Taxa de SaÌda ("000000000.00")';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DS_OPERACAO_REALIZADA" IS 'DescriÁ„o da operaÁ„o realizada';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."CD_ANGARIADOR" IS 'CÛdigo do angariador';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DS_AGENCIA" IS 'AgÍncia ou ponto de venda';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."VL_IDENTIFICACAO_CLIENTE" IS 'IdentificaÁ„o do cliente no parceiro';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NM_PRODUTO" IS 'Nome do Produto que foi vendido';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."CD_PLANO_PARCEIRO" IS 'CÛdigo do plano no parceiro';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."NU_PROTOCOLO" IS 'N˙mero do protocolo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."VL_NOMINAL" IS 'Valor Nominal da operaÁ„o';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DS_CGC_CPF_CLIENTE" IS 'CGC/CPF do cliente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."CD_MOVIMENTO_ICATU" IS 'CÛdigo do movimento na Icatu';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI"."DT_SOLICITACAO" IS 'Data de registro da solicitaÁ„o do movimento (yyyymmdd)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."PID_DOCUMENTO_PORTABILIDADE" IS 'IdentificaÁ„o da portabilidade';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."PID_SEGURADORA_CED" IS 'CÛdigo da seguradora cedente (Origem)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."PID_TIPO_PRODUTO" IS 'CÛdigo do tipo de fundo da cession·ria.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."PID_REGIME_TRIBUTARIO_CED" IS 'CÛdigo do tipo tribut·rio da cedente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."PID_TIPO_ENTIDADE_CED" IS 'CÛdigo do tipo de entidade do seguro da Cedente (aberta/fechada)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."VL_PORTABILIDADE" IS 'Valor da portabilidade';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."NM_PLANO_CED" IS 'DescriÁ„o do produto da Cedente.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE"."NUM_CERTIFICADO_CED" IS 'Codigo Certificado Cedente.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_FUNDO"."NM_FUNDO" IS '';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PARAMETRO_FTP"."TP_CONEXAO" IS '1 - FTP
2 - FTPS
3 - SFTP';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PLAN"."TP_REGISTRO" IS 'Fixo "1"';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PLAN"."NM_FUNDO" IS 'Nome do fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PLAN"."CD_FUNDO" IS 'CÛdigo do fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PLAN"."VL_DA" IS 'Valor da "DA" do fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO"."ID" IS 'Identificador ˙nico de cada endereÁo de uma pessoa.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO"."PID_TIPO_ENDERECO" IS 'Identificador do tipo de endereÁo.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO"."DS_ENDERECO" IS 'DescriÁ„o do endereÁo.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO"."DS_COMPLEMENTO" IS 'Complemento do endereÁo, quando for necess·rio informar.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO"."DS_BAIRRO" IS 'Bairro.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO"."NU_CEP" IS 'N˙mero do CEP.';
 COMMENT ON TABLE "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO"  IS 'Cadastro dos endereÁos de cada pessoa.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_USUARIO"."LOGIN_USUARIO" IS 'Nome de login usu·rio.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_USUARIO"."DS_SENHA" IS 'Senha criptografada do usu·rio.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQ_STATUS_CARGA"."TP_ARQUIVO" IS 'Tipo de arquivo:
1 = Arquivo Cada
2 = Arquivo Cota
3 = Arquivo Movi
4 = Arquivo Plan
5 = Arquivo Portabilidade';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQ_STATUS_CARGA"."VL_LINHA_INICIAL" IS 'Linha Inicial da carga, valido somente para Portabilidade';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PARAMETRO_BATCH"."TP_ARQUIVO" IS 'Tipo de arquivo:
1 = Arquivo Cada
2 = Arquivo Cota
3 = Arquivo Movi
4 = Arquivo Plan
5 = Arquivo Portabilidade';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_COTA"."TP_REGISTRO" IS 'Fixo "2"';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_COTA"."DT_INDICE" IS 'Data da cota';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_COTA"."CD_FUNDO" IS 'CÛdigo do fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_COTA"."VL_COTA" IS 'Valor da Cota (0000000.00000000)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_COTA"."VL_SALDO" IS 'Valor do Saldo do Fundo (0000000000.00)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO"."ID_DOCUMENTO" IS 'Identificador ˙nico de cada documento do seguro.';
 COMMENT ON TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO"  IS 'Cadastro de documentos que est„o ligados a um determinado seguro. S„o considerados como documentos do seguro as cotaÁıes, propostas, apÛlices e endossos.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."TP_ARQUIVO" IS 'Define o tipo do arquivo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."NU_PROPOSTA" IS 'N˙mero da proposta do cliente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."NU_MATRICULA" IS 'N˙mero da matrÌcula do cliente';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."NM_TITULAR" IS 'Nome do Titular';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DS_LOGRADOURO" IS 'Logradouro';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DS_BAIRRO" IS 'bairro';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DS_CIDADE" IS 'Cidade';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DS_CEP" IS 'CEP
';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DS_UF" IS 'Unidade da FederaÁ„o';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."NU_TELEFONE1" IS 'Telefone 1';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."NU_TELEFONE2" IS 'Telefone 2';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."NM_FUNDO" IS 'Nome do Fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."CD_FUNDO" IS 'CÛdigo do Fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."CT_FUNDO" IS 'CÛdigo de investimento do cliente no fundo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DT_SALDO" IS 'Data do Saldo (yyyymmdd)';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."QT_COTAS" IS 'Valor Saldo em Cotas na data do saldo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."VL_SALDO" IS 'Valor do Saldo';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DT_LIBERACAO_PORTABILIDADE" IS 'Data para LiberaÁ„o da Portabilidade';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DT_LIGERACAO_RESGATE" IS 'Data para LiberaÁ„o do Resgate';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."DS_SITUACAO" IS 'Status da situaÁ„o do Certificado para Emiss„o de CobranÁa
ACEITO PENDENTE DE ARRECADACAO
ACEITO
SUSPENSO
CANCELADO
PENDENTE DE ACEITACAO
RECUSADO
BLOQUEADO';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA"."NU_LINHA" IS 'Numero da linha no arquivo de carga.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PRODUTO"."ID" IS 'Identificador ˙nico de cada produto.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PRODUTO"."PID_RAMO" IS 'Identificador do ramo ao qual o produto pertence.';
 COMMENT ON COLUMN "DB_EXCHANGE_VISAO_TST"."TB_PRODUTO"."NM_PRODUTO" IS 'Nome do produto.';

-- Grants

PROMPT "Aplicando Grants"

GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_COMISSAO_LOG" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_PREVIDENCIA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_USUARIO_DIGITADOR" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_COBRANCA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_COMP_ALIQ" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_NIF" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA_PARAMETRO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PROPOSTA_COBERTURA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_USUARIO_CANAL_VENDA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_FORMA_PAGTO_EMPRESA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQ_PORTABILIDADE_INTERNA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_BENEFICIARIO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_SEGURADORA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_RESPONSAVEL_FINANCEIRO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_MOVI" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE_STATUS" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_HISTORICO_DOCUMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_FUNDO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_RESPONSAVEL_LEGAL" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PARAMETRO_FTP" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_NUM_DOCUMENTO_SEG" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_OBSERVACAO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQ_STATUS_CARGA_LOG" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PARAMETRIZACAO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_CIVIL" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PLAN" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_HISTORICO_DOC_CORRETOR" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ESTRUTURA_VENDA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PROPOSTA_FUNDO_INVESTIMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PRODUTO_EMPRESA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_COBERTURA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQ_STATUS_CARGA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PARAMETRO_BATCH" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_RISCO_PREFORMAT_COB" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_COMISSAO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_RISCO_PRE_FORMATADO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_MOTIVO_RECUSA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_GRUPO_FUNCIONALIDADE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_COMPRA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_CODIGO_ACESSO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_INVESTIMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_COTA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_CANAL_VENDA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQ_ALIQ" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_FUNDO_INVESTIMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_GRUPO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PAGAMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_CADA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PRODUTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PAIS" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_GRAU_PARENTESCO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_SEXO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_MOTIVO_NIF" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_PARAMETRO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_MOTIVO_RECUSA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_REGIME_TRIBUTARIO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_DOCUMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ESTADO_CIVIL" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_OCUPACAO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_SITUACAO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_INVESTIMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_DE_PARA_HISTORICO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_DIA_VENCIMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_ORGAO_EMISSOR" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_PORTABILIDADE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_ENTIDADE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_RISCO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_RAMO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TITULARIDADE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_FORMA_PAGAMENTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_SITUACAO_SEGURADORA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_MEIO_COMUNICACAO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_PRODUTO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_UF" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_FUNCIONALIDADE" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_BANCO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_ENDERECO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_VISAO" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_PERFIL" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_TIPO_EMPRESA" TO "CS_EXCHANGE_VISAO_HML";
GRANT SELECT ON "DB_EXCHANGE_VISAO_TST"."TB_LAYOUT_EMAIL" TO "CS_EXCHANGE_VISAO_HML";


prompt "Fim do Script CreateTable"

prompt "Carga Dados Tabelas NOVAS" 

REM INSERTING into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO
SET DEFINE OFF;
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('1','AJU','AJUSTE DE RENTABILIDADE','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('2','APL','CONTRIBUICAO - APLICACAO','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('3','ATI','REATIVACAO DE CERTIFICADO',null);
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('4','BLO','BLOQUEIO CERTIFICADO',null);
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('5','CDE','CANC. DEVOLUCAO PREMIO PAGO','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('6','CES','CANC. ESTORNO APLICACAO',null);
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('7','DA','DESPESA ADMINISTRATIVA','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('8','DDA','DEVOLUCAO D.A. ARRECADADA','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('9','DEV','DEVOLUCAO DE PREMIO PAGO','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('10','IFA','INCORPORACAO FUNDOS APL','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('11','IFS','INCORPORACAO DE FUNDOS SAIDA','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('12','IFT','INCORPORACAO FUNDOS TRANSF',null);
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('13','RES','RESGATE','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('14','TEE','TRANSFERENCIA EXTERNA -ENTRADA','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('15','TES','TRANSFERENCIA EXTERNA - SAIDA','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('16','TIE','MUDANCA DE FUNDO -  ENTRADA','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('17','TIP','TRANSFERENCIA INTERNA -ENTRADA','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('18','TIS','MUDANCA DE FUNDO - SAIDA','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('19','TRS','TRANSFERENCIA RESERVA SAIDA','N');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('20','UNI','UNIFICACAO DE MATRICULA',null);
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('21','URE','UNIFICACAO  RESERVA ENTRADA','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_DE_PARA_HISTORICO (ID,DS_CODIGO,DS_DESCRICAO,FL_POSITIVO) values ('22','URS','UNIFICACAO  RESERVA SAIDA','N');
commit;

REM INSERTING into DB_EXCHANGE_VISAO_DSV.TB_MOTIVO_NIF
SET DEFINE OFF;
Insert into DB_EXCHANGE_VISAO_DSV.TB_MOTIVO_NIF (ID,DS_MOTIVO) values ('1','País não emite NIF');
Insert into DB_EXCHANGE_VISAO_DSV.TB_MOTIVO_NIF (ID,DS_MOTIVO) values ('2','Não consigo obter NIF');
Insert into DB_EXCHANGE_VISAO_DSV.TB_MOTIVO_NIF (ID,DS_MOTIVO) values ('3','As autoridades fiscais não exigem');
commit;

REM INSERTING into DB_EXCHANGE_VISAO_DSV.TB_TIPO_INVESTIMENTO
SET DEFINE OFF;
Insert into DB_EXCHANGE_VISAO_DSV.TB_TIPO_INVESTIMENTO (ID,DESCRICAO) values ('1','Fundo Simples');
Insert into DB_EXCHANGE_VISAO_DSV.TB_TIPO_INVESTIMENTO (ID,DESCRICAO) values ('2','Carteira Fixa');
Insert into DB_EXCHANGE_VISAO_DSV.TB_TIPO_INVESTIMENTO (ID,DESCRICAO) values ('3','Carteira Variável');
commit;

REM INSERTING into DB_EXCHANGE_VISAO_DSV.TB_TIPO_RISCO
SET DEFINE OFF;
Insert into DB_EXCHANGE_VISAO_DSV.TB_TIPO_RISCO (ID,DS_TIPO_RISCO,FL_ATIVO) values ('1','CONSERVADOR','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_TIPO_RISCO (ID,DS_TIPO_RISCO,FL_ATIVO) values ('2','MODERADO','S');
Insert into DB_EXCHANGE_VISAO_DSV.TB_TIPO_RISCO (ID,DS_TIPO_RISCO,FL_ATIVO) values ('3','ARROJADO','S');
commit;


spool off

exit 
