-- Script de criação dos índices e constraints(PKs,UKs e FKs)
-- Autor: Alexandre e Rogerio
-- Favor informar antes de executar o script o schema que será usado para receber os objeetos

-- Indexes

/************************************
*  INPUT PARAMETERS
************************************/
DEFINE owner=DB_EXCHANGE_VISAO_TST

alter session set current_schema = &owner;

spool create_tables_IndexConstr.log

CREATE UNIQUE INDEX "TB_MOTIVO_RECUSA_PK" ON "TB_MOTIVO_RECUSA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_MOTIVO_RECUSA_PK";
CREATE UNIQUE INDEX "TB_TIPO_INVESTIMENTO_PK" ON "TB_TIPO_INVESTIMENTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_TIPO_INVESTIMENTO_PK";
CREATE UNIQUE INDEX "FUNCIONALIDADE_PK" ON "TB_FUNCIONALIDADE" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "FUNCIONALIDADE_PK";
CREATE UNIQUE INDEX "CP_PERFIL" ON "TB_PERFIL" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_PERFIL";
CREATE UNIQUE INDEX "TB_RESPONSAVEL_FINANCEIRO_PK" ON "TB_RESPONSAVEL_FINANCEIRO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_RESPONSAVEL_FINANCEIRO_PK";
CREATE UNIQUE INDEX "TB_RESPONSAVEL_LEGAL_PK" ON "TB_RESPONSAVEL_LEGAL" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_RESPONSAVEL_LEGAL_PK";
CREATE UNIQUE INDEX "TB_PARAMETRIZACAO_PK" ON "TB_PARAMETRIZACAO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PARAMETRIZACAO_PK";
CREATE INDEX "TB_PESSOA_ENDERECO_N3" ON "TB_ENDERECO" ("PID_TIPO_ENDERECO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PESSOA_ENDERECO_N3";
CREATE UNIQUE INDEX "CP_PESSOA_ENDERECO" ON "TB_ENDERECO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_PESSOA_ENDERECO";
CREATE UNIQUE INDEX "TB_PRODUTO_EMPRESA_PK" ON "TB_PRODUTO_EMPRESA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PRODUTO_EMPRESA_PK";
CREATE INDEX "TB_COMISSAO_N2" ON "TB_COMISSAO" ("NM_SEGURADO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST" 
 ;

  ALTER INDEX "TB_COMISSAO_N2" PARALLEL 6;
CREATE INDEX "TB_COMISSAO_N1" ON "TB_COMISSAO" ("CD_PROCESSO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST" 
 ;

  ALTER INDEX "TB_COMISSAO_N1" PARALLEL 6;
CREATE UNIQUE INDEX "CP_COMISSAO" ON "TB_COMISSAO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST" 
 ;

  ALTER INDEX "CP_COMISSAO" PARALLEL 6;
CREATE UNIQUE INDEX "TB_COMPRA_PK" ON "TB_COMPRA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_COMPRA_PK";
CREATE UNIQUE INDEX "TB_COMPRA_UK1" ON "TB_COMPRA" ("UUID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_COMPRA_UK1";
CREATE UNIQUE INDEX "ARQ_ALIQ_PK" ON "TB_ARQ_ALIQ" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "ARQ_ALIQ_PK";
CREATE INDEX "IDX_TB_HISTORICO_DOCUMENTO_01" ON "TB_HISTORICO_DOCUMENTO" ("PID_DOCUMENTO", "ID", "PID_SITUACAO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "IDX_TB_HISTORICO_DOCUMENTO_01";
CREATE UNIQUE INDEX "TB_HISTORICO_DOCUMENTO_PK" ON "TB_HISTORICO_DOCUMENTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_HISTORICO_DOCUMENTO_PK";
CREATE UNIQUE INDEX "CP_RAMO" ON "TB_RAMO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_RAMO";
CREATE UNIQUE INDEX "COMP_ALIQ_PK" ON "TB_COMP_ALIQ" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "COMP_ALIQ_PK";
CREATE UNIQUE INDEX "CP_SEGURO_BENEFICIARIO" ON "TB_DOCUMENTO_BENEFICIARIO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_SEGURO_BENEFICIARIO";
CREATE UNIQUE INDEX "TB_CODIGO_ACESSO_PK" ON "TB_CODIGO_ACESSO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_CODIGO_ACESSO_PK";
CREATE UNIQUE INDEX "TB_INVESTIMENTO_PK" ON "TB_INVESTIMENTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_INVESTIMENTO_PK";
CREATE UNIQUE INDEX "TB_SEXO_PK" ON "TB_SEXO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_SEXO_PK";
CREATE UNIQUE INDEX "TB_PAIS_PK" ON "TB_PAIS" ("CD_PAIS") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PAIS_PK";
CREATE INDEX "IDX_TB_PORTABILIDADE_STATUS_01" ON "TB_PORTABILIDADE_STATUS" ("ID", "PID_PORTABILIDADE") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "IDX_TB_PORTABILIDADE_STATUS_01";
CREATE UNIQUE INDEX "TB_PORTABILIDADE_STATUS_PK" ON "TB_PORTABILIDADE_STATUS" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PORTABILIDADE_STATUS_PK";
CREATE UNIQUE INDEX "TB_DE_PARA_HISTORICO_PK" ON "TB_DE_PARA_HISTORICO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_DE_PARA_HISTORICO_PK";
CREATE UNIQUE INDEX "TB_TIPO_RISCO_PK" ON "TB_TIPO_RISCO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_TIPO_RISCO_PK";
CREATE UNIQUE INDEX "VISAO_PK" ON "TB_VISAO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "VISAO_PK";
CREATE UNIQUE INDEX "SYS_C00381553" ON "TB_DOCUMENTO_PREVIDENCIA" ("PID_DOCUMENTO_PREVIDENCIA") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "SYS_C00381553";
CREATE UNIQUE INDEX "TB_USUARIO_CANAL_VENDA_PK" ON "TB_USUARIO_CANAL_VENDA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_USUARIO_CANAL_VENDA_PK";
CREATE UNIQUE INDEX "TB_SEGURADORA_PK" ON "TB_SEGURADORA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_SEGURADORA_PK";
CREATE UNIQUE INDEX "TB_DOCUMENTO_PK" ON "TB_DOCUMENTO_CIVIL" ("CD_DOCUMENTO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_DOCUMENTO_PK";
CREATE UNIQUE INDEX "CU_USUARIO_01" ON "TB_USUARIO" ("PID_EMPRESA", "NU_CPF_CNPJ") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CU_USUARIO_01";
CREATE UNIQUE INDEX "CP_USUARIO" ON "TB_USUARIO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_USUARIO";
CREATE UNIQUE INDEX "TB_USUARIO_UK1" ON "TB_USUARIO" ("PID_EMPRESA", "LOGIN_USUARIO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_USUARIO_UK1";
CREATE INDEX "TB_USUARIO_N1" ON "TB_USUARIO" ("PID_PERFIL") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_USUARIO_N1";
CREATE UNIQUE INDEX "TB_TIPO_MOTIVO_RECUSA_PK" ON "TB_TIPO_MOTIVO_RECUSA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_TIPO_MOTIVO_RECUSA_PK";
CREATE UNIQUE INDEX "TABLE1_PK1" ON "TB_ARQUIVO_COTA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TABLE1_PK1";
CREATE INDEX "IDX_TB_DOCUMENTO_01" ON "TB_DOCUMENTO" ("NUM_DOC_SEG") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "IDX_TB_DOCUMENTO_01";
CREATE UNIQUE INDEX "CP_SEGURO_DOCUMENTO" ON "TB_DOCUMENTO" ("ID_DOCUMENTO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_SEGURO_DOCUMENTO";
CREATE UNIQUE INDEX "TB_PORTABILIDADE_PK" ON "TB_PORTABILIDADE" ("PID_DOCUMENTO_PORTABILIDADE") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PORTABILIDADE_PK";
CREATE UNIQUE INDEX "TB_PV_TIPO_PORTABLIDADE_PK" ON "TB_TIPO_PORTABILIDADE" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PV_TIPO_PORTABLIDADE_PK";
CREATE UNIQUE INDEX "TB_TIPO_ENTIDADE_PK" ON "TB_TIPO_ENTIDADE" ("CD_TIPO_ENTIDADE") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_TIPO_ENTIDADE_PK";
CREATE UNIQUE INDEX "TB_TITULARIDADE_PK" ON "TB_TITULARIDADE" ("CD_TITULARIDADE") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_TITULARIDADE_PK";
CREATE UNIQUE INDEX "ID_SITUACAO_SEG_PK" ON "TB_SITUACAO_SEGURADORA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "ID_SITUACAO_SEG_PK";
CREATE UNIQUE INDEX "TB_BANCO_PK" ON "TB_BANCO" ("CD_BANCO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_BANCO_PK";
CREATE UNIQUE INDEX "CP_TIPO_ENDERECO" ON "TB_TIPO_ENDERECO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_TIPO_ENDERECO";
CREATE UNIQUE INDEX "TB_TIPO_EMPRESA_PK" ON "TB_TIPO_EMPRESA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_TIPO_EMPRESA_PK";
CREATE UNIQUE INDEX "TB_LAYOUT_EMAIL_PK" ON "TB_LAYOUT_EMAIL" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_LAYOUT_EMAIL_PK";
CREATE UNIQUE INDEX "TB_SEGURO_COBRANCA_PK" ON "TB_DOCUMENTO_COBRANCA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_SEGURO_COBRANCA_PK";
CREATE UNIQUE INDEX "TB_ARQUIVO_PORTABILIDADE_PK" ON "TB_ARQUIVO_PORTABILIDADE" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_ARQUIVO_PORTABILIDADE_PK";
CREATE UNIQUE INDEX "TB_CLIENTE_NIF_PK" ON "TB_NIF" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_CLIENTE_NIF_PK";
CREATE UNIQUE INDEX "TB_EMPRESA_PARAMETRO_PK" ON "TB_EMPRESA_PARAMETRO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_EMPRESA_PARAMETRO_PK";
CREATE UNIQUE INDEX "TB_OBSERVACAO_PK" ON "TB_OBSERVACAO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_OBSERVACAO_PK";
CREATE UNIQUE INDEX "TB_COBERTURA_PK" ON "TB_COBERTURA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_COBERTURA_PK";
CREATE UNIQUE INDEX "GRUPO_FUNCIONALIDADE_PK" ON "TB_GRUPO_FUNCIONALIDADE" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "GRUPO_FUNCIONALIDADE_PK";
CREATE INDEX "IDX_TB_ARQUIVO_CADA_02" ON "TB_ARQUIVO_CADA" ("NU_PROPOSTA", "PID_ARQ_STATUS") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "IDX_TB_ARQUIVO_CADA_02";
CREATE INDEX "IDX_TB_ARQUIVO_CADA_01" ON "TB_ARQUIVO_CADA" ("NU_PROPOSTA") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "IDX_TB_ARQUIVO_CADA_01";
CREATE UNIQUE INDEX "TB_ARQUIVO_CADA_PK" ON "TB_ARQUIVO_CADA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_ARQUIVO_CADA_PK";
CREATE UNIQUE INDEX "TB_MOTIVO_NIF_PK" ON "TB_MOTIVO_NIF" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_MOTIVO_NIF_PK";
CREATE UNIQUE INDEX "CU_UF1" ON "TB_UF" ("NM_UF") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CU_UF1";
CREATE UNIQUE INDEX "CP_UF" ON "TB_UF" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_UF";
CREATE UNIQUE INDEX "TB_NUM_DOCUMENTO_SEG_PK" ON "TB_NUM_DOCUMENTO_SEG" ("NUM_DOCUMENTO_SEG") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_NUM_DOCUMENTO_SEG_PK";
CREATE UNIQUE INDEX "TB_PROP_FUNDO_INVEST_PK" ON "TB_PROPOSTA_FUNDO_INVESTIMENTO" ("NUM_DOC_SEG") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PROP_FUNDO_INVEST_PK";
CREATE UNIQUE INDEX "TB_RISCO_PREFORMAT_COB_PK" ON "TB_RISCO_PREFORMAT_COB" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_RISCO_PREFORMAT_COB_PK";
CREATE UNIQUE INDEX "GRUPO_PK" ON "TB_GRUPO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "GRUPO_PK";
CREATE UNIQUE INDEX "TB_GRAU_PARENTESCO_PK" ON "TB_GRAU_PARENTESCO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_GRAU_PARENTESCO_PK";
CREATE UNIQUE INDEX "TB_REGIME_TRIBUTARIO_PK" ON "TB_REGIME_TRIBUTARIO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_REGIME_TRIBUTARIO_PK";
CREATE UNIQUE INDEX "TB_TIPO_PRODUTO_PK" ON "TB_TIPO_PRODUTO" ("CD_TIPO_PRODUTO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_TIPO_PRODUTO_PK";
CREATE UNIQUE INDEX "TB_ARQ_STATUS_CARGA_LOG_PK" ON "TB_ARQ_STATUS_CARGA_LOG" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_ARQ_STATUS_CARGA_LOG_PK";
CREATE INDEX "IDX_TB_ARQ_STATUS_CARGA_01" ON "TB_ARQ_STATUS_CARGA" ("ID", "DT_CARGA") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "IDX_TB_ARQ_STATUS_CARGA_01";
CREATE UNIQUE INDEX "SYS_C00180359" ON "TB_ARQ_STATUS_CARGA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "SYS_C00180359";
CREATE UNIQUE INDEX "TB_EMPRESA_PK" ON "TB_EMPRESA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_EMPRESA_PK";
CREATE UNIQUE INDEX "CP_TIPO_SEGURO_DOCUMENTO" ON "TB_TIPO_DOCUMENTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_TIPO_SEGURO_DOCUMENTO";
CREATE UNIQUE INDEX "TB_SITUACAO_SEGURADORA_PK" ON "TB_SITUACAO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_SITUACAO_SEGURADORA_PK";
CREATE UNIQUE INDEX "TB_DIA_VENCIMENTO_PK" ON "TB_DIA_VENCIMENTO" ("ID_DIA_VENCIMENTO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_DIA_VENCIMENTO_PK";
CREATE UNIQUE INDEX "TB_ARQUIVO_MOVI_PK" ON "TB_ARQUIVO_MOVI" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_ARQUIVO_MOVI_PK";
CREATE INDEX "IDX_TB_CLIENTE_01" ON "TB_CLIENTE" ("PID_SEXO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "IDX_TB_CLIENTE_01";
CREATE UNIQUE INDEX "CP_CLIENTE" ON "TB_CLIENTE" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_CLIENTE";
CREATE UNIQUE INDEX "TB_ARQUIVO_PLAN_PK" ON "TB_ARQUIVO_PLAN" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_ARQUIVO_PLAN_PK";
CREATE UNIQUE INDEX "ESTRUTURA_VENDA_PK" ON "TB_ESTRUTURA_VENDA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "ESTRUTURA_VENDA_PK";
CREATE INDEX "TB_CANAL_VENDA_N1" ON "TB_CANAL_VENDA" ("PID_EMPRESA") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_CANAL_VENDA_N1";
CREATE UNIQUE INDEX "CU_CANAL_VENDA_01" ON "TB_CANAL_VENDA" ("PID_EMPRESA", "NM_CANAL_VENDA") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CU_CANAL_VENDA_01";
CREATE UNIQUE INDEX "CP_CANAL_VENDA" ON "TB_CANAL_VENDA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_CANAL_VENDA";
CREATE UNIQUE INDEX "TB_FUNDO_INVESTIMENTO_PK" ON "TB_FUNDO_INVESTIMENTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_FUNDO_INVESTIMENTO_PK";
CREATE UNIQUE INDEX "TB_ARQUIVO_PAGAMENTO_PK" ON "TB_ARQUIVO_PAGAMENTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_ARQUIVO_PAGAMENTO_PK";
CREATE INDEX "TB_PRODUTO_N1" ON "TB_PRODUTO" ("PID_RAMO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PRODUTO_N1";
CREATE UNIQUE INDEX "CP_PRODUTO" ON "TB_PRODUTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_PRODUTO";
CREATE UNIQUE INDEX "TB_PV_FUNDO_PK" ON "TB_FUNDO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_PV_FUNDO_PK";
CREATE UNIQUE INDEX "CP_ESTADO_CIVIL" ON "TB_ESTADO_CIVIL" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_ESTADO_CIVIL";
CREATE UNIQUE INDEX "TB_OCUPACAO_PK" ON "TB_OCUPACAO" ("CD_OCUPACAO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_OCUPACAO_PK";
CREATE UNIQUE INDEX "TB_ORGAO_EMISSOR_PK" ON "TB_ORGAO_EMISSOR" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_ORGAO_EMISSOR_PK";
CREATE UNIQUE INDEX "CP_FORMA_PAGAMENTO" ON "TB_FORMA_PAGAMENTO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_FORMA_PAGAMENTO";
CREATE UNIQUE INDEX "CP_MEIO_COMUNICACAO" ON "TB_TIPO_MEIO_COMUNICACAO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CP_MEIO_COMUNICACAO";
CREATE UNIQUE INDEX "CU_MEIO_COMUNICACAO" ON "TB_TIPO_MEIO_COMUNICACAO" ("NM_MEIO_COMUNICACAO") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "CU_MEIO_COMUNICACAO";
CREATE UNIQUE INDEX "FORMA_PAGTO_EMPRESA_PK" ON "TB_FORMA_PAGTO_EMPRESA" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "FORMA_PAGTO_EMPRESA_PK";
CREATE UNIQUE INDEX "TB_RISCO_PRE_FORMATADO_PK" ON "TB_RISCO_PRE_FORMATADO" ("ID") 
  TABLESPACE "DB_EXCHANGE_VISAO_TST";

  ALTER INDEX "TB_RISCO_PRE_FORMATADO_PK";

  -- Constraints

ALTER TABLE "TB_DOCUMENTO_BENEFICIARIO" ADD CONSTRAINT "TB_DOCUMENTO_BENEFICIARIO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_DE_PARA_HISTORICO" ADD CONSTRAINT "TB_DE_PARA_HISTORICO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_RAMO" ADD CONSTRAINT "CP_RAMO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PAIS" ADD CONSTRAINT "TB_PAIS_PK" PRIMARY KEY ("CD_PAIS") ENABLE;
ALTER TABLE "TB_REGIME_TRIBUTARIO" ADD CONSTRAINT "TB_REGIME_TRIBUTARIO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TITULARIDADE" ADD CONSTRAINT "TB_TITULARIDADE_PK" PRIMARY KEY ("CD_TITULARIDADE") ENABLE;
ALTER TABLE "TB_TIPO_DOCUMENTO" ADD CONSTRAINT "CP_TIPO_SEGURO_DOCUMENTO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_GRAU_PARENTESCO" ADD CONSTRAINT "TB_GRAU_PARENTESCO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ESTADO_CIVIL" ADD CONSTRAINT "CP_ESTADO_CIVIL" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_SEXO" ADD CONSTRAINT "TB_SEXO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_DIA_VENCIMENTO" ADD CONSTRAINT "TB_DIA_VENCIMENTO_PK" PRIMARY KEY ("ID_DIA_VENCIMENTO") ENABLE;
ALTER TABLE "TB_ORGAO_EMISSOR" ADD CONSTRAINT "TB_ORGAO_EMISSOR_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_OCUPACAO" ADD CONSTRAINT "TB_OCUPACAO_PK" PRIMARY KEY ("CD_OCUPACAO") ENABLE;
ALTER TABLE "TB_SITUACAO" ADD CONSTRAINT "TB_SITUACAO_SEGURADORA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_PORTABILIDADE" ADD CONSTRAINT "TB_PV_TIPO_PORTABLIDADE_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_MOTIVO_RECUSA" ADD CONSTRAINT "TB_MOTIVO_RECUSA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_ENTIDADE" ADD CONSTRAINT "TB_TIPO_ENTIDADE_PK" PRIMARY KEY ("CD_TIPO_ENTIDADE") ENABLE;
ALTER TABLE "TB_MOTIVO_NIF" ADD CONSTRAINT "TB_MOTIVO_NIF_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_RISCO" ADD CONSTRAINT "TB_TIPO_RISCO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_INVESTIMENTO" ADD CONSTRAINT "TB_TIPO_INVESTIMENTO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_VISAO" ADD CONSTRAINT "VISAO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_FORMA_PAGAMENTO" ADD CONSTRAINT "CP_FORMA_PAGAMENTO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_SITUACAO_SEGURADORA" ADD CONSTRAINT "ID_SITUACAO_SEG_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_UF" ADD CONSTRAINT "CU_UF1" UNIQUE ("NM_UF")
  USING INDEX "CU_UF1"  ENABLE;
ALTER TABLE "TB_UF" ADD CONSTRAINT "CP_UF" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_UF" ADD CONSTRAINT "CK_UF_01" CHECK (DS_UF = UPPER(DS_UF)) ENABLE;
ALTER TABLE "TB_FUNCIONALIDADE" ADD CONSTRAINT "FUNCIONALIDADE_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PERFIL" ADD CONSTRAINT "CP_PERFIL" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_ENDERECO" ADD CONSTRAINT "CP_TIPO_ENDERECO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_EMPRESA" ADD CONSTRAINT "TB_TIPO_EMPRESA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_BANCO" ADD CONSTRAINT "TB_BANCO_PK" PRIMARY KEY ("CD_BANCO") ENABLE;
ALTER TABLE "TB_TIPO_MEIO_COMUNICACAO" ADD CONSTRAINT "CU_MEIO_COMUNICACAO" UNIQUE ("NM_MEIO_COMUNICACAO") ENABLE;
ALTER TABLE "TB_TIPO_MEIO_COMUNICACAO" ADD CONSTRAINT "CP_MEIO_COMUNICACAO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_LAYOUT_EMAIL" ADD CONSTRAINT "TB_LAYOUT_EMAIL_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_PRODUTO" ADD CONSTRAINT "TB_TIPO_PRODUTO_PK" PRIMARY KEY ("CD_TIPO_PRODUTO") ENABLE;
ALTER TABLE "TB_ARQUIVO_PORTABILIDADE" ADD CONSTRAINT "TB_ARQUIVO_PORTABILIDADE_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_FUNDO_INVESTIMENTO" ADD CONSTRAINT "TB_FUNDO_INVESTIMENTO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ARQ_ALIQ" ADD CONSTRAINT "ARQ_ALIQ_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_COMP_ALIQ" ADD CONSTRAINT "COMP_ALIQ_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_INVESTIMENTO" ADD CONSTRAINT "TB_INVESTIMENTO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_RISCO_PREFORMAT_COB" ADD CONSTRAINT "TB_RISCO_PREFORMAT_COB_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_RESPONSAVEL_LEGAL" ADD CONSTRAINT "TB_RESPONSAVEL_LEGAL_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_RESPONSAVEL_FINANCEIRO" ADD CONSTRAINT "TB_RESPONSAVEL_FINANCEIRO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ESTRUTURA_VENDA" ADD CONSTRAINT "ESTRUTURA_VENDA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_USUARIO" ADD CONSTRAINT "TB_USUARIO_UK1" UNIQUE ("PID_EMPRESA", "LOGIN_USUARIO")
  USING INDEX "TB_USUARIO_UK1"  ENABLE;
ALTER TABLE "TB_USUARIO" ADD CONSTRAINT "CK_USUARIO_01" CHECK (FL_PRIMEIRO_ACESSO IN ('S','N')) ENABLE;
ALTER TABLE "TB_USUARIO" ADD CONSTRAINT "CK_USUARIO_02" CHECK (FL_BLOQUEADO IN ('S','N')) ENABLE;
ALTER TABLE "TB_USUARIO" ADD CONSTRAINT "CK_USUARIO_03" CHECK (FL_ATIVO IN ('S','N')) ENABLE;
ALTER TABLE "TB_USUARIO" ADD CONSTRAINT "CP_USUARIO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_CLIENTE" ADD CONSTRAINT "CP_CLIENTE" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PARAMETRIZACAO" ADD CONSTRAINT "TB_PARAMETRIZACAO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_DOCUMENTO" ADD CONSTRAINT "CP_SEGURO_DOCUMENTO" PRIMARY KEY ("ID_DOCUMENTO") ENABLE;
ALTER TABLE "TB_ARQ_STATUS_CARGA_LOG" ADD CONSTRAINT "TB_ARQ_STATUS_CARGA_LOG_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_TIPO_MOTIVO_RECUSA" ADD CONSTRAINT "TB_TIPO_MOTIVO_RECUSA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_DOCUMENTO_COBRANCA" ADD CONSTRAINT "TB_SEGURO_COBRANCA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_GRUPO" ADD CONSTRAINT "GRUPO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PRODUTO_EMPRESA" ADD CONSTRAINT "TB_PRODUTO_EMPRESA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_USUARIO" ADD CONSTRAINT "CK_VISAO_LOGADA" CHECK ("FL_VISAO_LOGADA"='N' OR "FL_VISAO_LOGADA"='S') ENABLE;
ALTER TABLE "TB_ARQUIVO_PAGAMENTO" ADD CONSTRAINT "TB_ARQUIVO_PAGAMENTO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PRODUTO" ADD CONSTRAINT "ID" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ARQUIVO_CADA" ADD CONSTRAINT "TB_ARQUIVO_CADA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_CANAL_VENDA" ADD CONSTRAINT "CP_CANAL_VENDA" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PORTABILIDADE" ADD CONSTRAINT "TB_DOCUMENTO_PORTABILIDADE_PK" PRIMARY KEY ("PID_DOCUMENTO_PORTABILIDADE") ENABLE;
ALTER TABLE "TB_COMISSAO" ADD CONSTRAINT "CP_COMISSAO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ARQUIVO_COTA" ADD CONSTRAINT "TB_ARQUIVO_COTA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_FUNDO" ADD CONSTRAINT "TB_PV_FUNDO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PORTABILIDADE_STATUS" ADD CONSTRAINT "TB_PORTABILIDADE_STATUS_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_CODIGO_ACESSO" ADD CONSTRAINT "TB_CODIGO_ACESSO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ARQUIVO_PLAN" ADD CONSTRAINT "TB_ARQUIVO_PLAN_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_DOCUMENTO_CIVIL" ADD CONSTRAINT "TB_DOCUMENTO_PK" PRIMARY KEY ("CD_DOCUMENTO") ENABLE;
ALTER TABLE "TB_ARQUIVO_MOVI" ADD CONSTRAINT "TB_ARQUIVO_MOVI_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_NUM_DOCUMENTO_SEG" ADD CONSTRAINT "TB_NUM_DOCUMENTO_SEG_PK" PRIMARY KEY ("NUM_DOCUMENTO_SEG") ENABLE;
ALTER TABLE "TB_FORMA_PAGTO_EMPRESA" ADD CONSTRAINT "FORMA_PAGTO_EMPRESA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_COMPRA" ADD CONSTRAINT "TB_COMPRA_UK1" UNIQUE ("UUID")
  USING INDEX "TB_COMPRA_UK1"  ENABLE;
ALTER TABLE "TB_COMPRA" ADD CONSTRAINT "TB_COMPRA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_COBERTURA" ADD CONSTRAINT "TB_COBERTURA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_OBSERVACAO" ADD CONSTRAINT "TB_OBSERVACAO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_PROPOSTA_FUNDO_INVESTIMENTO" ADD CONSTRAINT "TB_PROP_FUNDO_INVEST_PK" PRIMARY KEY ("NUM_DOC_SEG") ENABLE;
ALTER TABLE "TB_EMPRESA_PARAMETRO" ADD CONSTRAINT "TB_EMPRESA_PARAMETRO_PK" PRIMARY KEY ("ID")
  USING INDEX "TB_EMPRESA_PARAMETRO_PK"  ENABLE;
ALTER TABLE "TB_RISCO_PRE_FORMATADO" ADD CONSTRAINT "TB_RISCO_PRE_FORMATADO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_GRUPO_FUNCIONALIDADE" ADD CONSTRAINT "GRUPO_FUNCIONALIDADE_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_USUARIO_CANAL_VENDA" ADD CONSTRAINT "TB_USUARIO_CANAL_VENDA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_HISTORICO_DOCUMENTO" ADD CONSTRAINT "TB_HISTORICO_DOCUMENTO_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_HISTORICO_DOC_CORRETOR" ADD PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ARQ_STATUS_CARGA" ADD PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_SEGURADORA" ADD CONSTRAINT "TB_SEGURADORA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_ENDERECO" ADD CONSTRAINT "CP_PESSOA_ENDERECO" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_DOCUMENTO_PREVIDENCIA" ADD CONSTRAINT "SYS_C00381553" PRIMARY KEY ("PID_DOCUMENTO_PREVIDENCIA") ENABLE;
ALTER TABLE "TB_COMISSAO_LOG" ADD CONSTRAINT "CP_COMISSAO_LOG" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_EMPRESA" ADD CONSTRAINT "TB_EMPRESA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "TB_NIF" ADD CONSTRAINT "TB_CLIENTE_NIF_PK" PRIMARY KEY ("ID") ENABLE;

-- Ref Constraints 

ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_MOTIVO_RECUSA" ADD CONSTRAINT "CD_MOTIVO_RECUSA_FK1" FOREIGN KEY ("PID_TIPO_MOTIVO_RECUSA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_MOTIVO_RECUSA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_SITUACAO_SEGURADORA" ADD CONSTRAINT "TIPO_DOCUMENTO_FK" FOREIGN KEY ("PID_TIPO_DOCUMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_DOCUMENTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_PREVIDENCIA" ADD CONSTRAINT "TB_DOC_REGIME_TRIBUTARIO_FK2" FOREIGN KEY ("PID_REGIME_TRIBUTARIO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_REGIME_TRIBUTARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_PREVIDENCIA" ADD CONSTRAINT "TB_DOCUMENTO_PREVIDENCIA_FK1" FOREIGN KEY ("PID_DOCUMENTO_PREVIDENCIA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ("ID_DOCUMENTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO_DIGITADOR" ADD CONSTRAINT "USUARIO_CORRETOR_FK" FOREIGN KEY ("PID_USUARIO_CORRETOR")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO_DIGITADOR" ADD CONSTRAINT "USUARIO_DIGITADOR_FK" FOREIGN KEY ("PID_USUARIO_DIGITADOR")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_COBRANCA" ADD CONSTRAINT "TB_DOCUMENTO_COBRANCA_FK1" FOREIGN KEY ("PID_DOCUMENTO_PREVIDENCIA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_PREVIDENCIA" ("PID_DOCUMENTO_PREVIDENCIA") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_COBRANCA" ADD CONSTRAINT "TB_SEG_COB_FK3" FOREIGN KEY ("PID_FORMA_PAGAMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_FORMA_PAGAMENTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_COBRANCA" ADD CONSTRAINT "TB_SEG_COB_BANCO_FK2" FOREIGN KEY ("PID_BANCO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_BANCO" ("CD_BANCO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_COBRANCA" ADD CONSTRAINT "TB_SEG_COB_VENCIMENTO_FK4" FOREIGN KEY ("PID_DIA_VENCIMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DIA_VENCIMENTO" ("ID_DIA_VENCIMENTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_ARQUIVO_PORTABILIDADE" ADD CONSTRAINT "FK_CJWER3QJ3V8IA2X1S73SITV3C" FOREIGN KEY ("PID_MOTIVO_RECUSA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_MOTIVO_RECUSA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_COMP_ALIQ" ADD CONSTRAINT "ARQ_ALIQ_FK" FOREIGN KEY ("PID_ARQ_ALIQ")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_ARQ_ALIQ" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_NIF" ADD CONSTRAINT "TB_CLIENTE_NIF_CLIENTE_FK2" FOREIGN KEY ("PID_CLIENTE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_NIF" ADD CONSTRAINT "TB_CLIENTE_NIF_PAIS_FK1" FOREIGN KEY ("PID_PAIS")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_PAIS" ("CD_PAIS") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_NIF" ADD CONSTRAINT "TB_NIF_TB_MOTIVO_NIF_FK" FOREIGN KEY ("PID_MOTIVO_NIF")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_MOTIVO_NIF" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA_PARAMETRO" ADD CONSTRAINT "TB_EMPRESA_FK" FOREIGN KEY ("PID_EMPRESA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PROPOSTA_COBERTURA" ADD CONSTRAINT "TB_COBERTURA_FKV1" FOREIGN KEY ("PID_COBERTURA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_COBERTURA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PROPOSTA_COBERTURA" ADD CONSTRAINT "TB_RISCO_PREFORMAT_COB_FK" FOREIGN KEY ("PID_RISCO_PREFORMAT_COB")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_RISCO_PREFORMAT_COB" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PROPOSTA_COBERTURA" ADD CONSTRAINT "TB_DOCUMENTO_FK" FOREIGN KEY ("PID_DOCUMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ("ID_DOCUMENTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO_CANAL_VENDA" ADD CONSTRAINT "TB_US_CANAL_USUARIO_FK1" FOREIGN KEY ("PID_USUARIO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO_CANAL_VENDA" ADD CONSTRAINT "TB_US_CANAL_FK1" FOREIGN KEY ("PID_CANAL_VENDA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_CANAL_VENDA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_FORMA_PAGTO_EMPRESA" ADD CONSTRAINT "EMPRESA_FK" FOREIGN KEY ("PID_EMPRESA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_FORMA_PAGTO_EMPRESA" ADD CONSTRAINT "TB_FORMA_PAGAMENTO_FK" FOREIGN KEY ("PID_FORMA_PAGAMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_FORMA_PAGAMENTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_BENEFICIARIO" ADD CONSTRAINT "TB_DOCUMENTO_BENEFICIARIO_FK2" FOREIGN KEY ("PID_DOCUMENTO_PREVIDENCIA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_PREVIDENCIA" ("PID_DOCUMENTO_PREVIDENCIA") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_BENEFICIARIO" ADD CONSTRAINT "TB_DOCUMENTO_BENEFICIARIO_FK1" FOREIGN KEY ("PID_GRAU_PARENTESCO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_GRAU_PARENTESCO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_RESPONSAVEL_FINANCEIRO" ADD CONSTRAINT "TB_RESPL_FIN_FK1" FOREIGN KEY ("PID_CLIENTE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ADD CONSTRAINT "REGIME_TRIBUTARIO_CED_FK" FOREIGN KEY ("PID_REGIME_TRIBUTARIO_CED")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_REGIME_TRIBUTARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ADD CONSTRAINT "SEGURADORA_CED_FK" FOREIGN KEY ("PID_SEGURADORA_CED")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_SEGURADORA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ADD CONSTRAINT "TIPO_ENTIDADE_CED_FK" FOREIGN KEY ("PID_TIPO_ENTIDADE_CED")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_ENTIDADE" ("CD_TIPO_ENTIDADE") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ADD CONSTRAINT "TIPO_PORTABILIDADE_FK" FOREIGN KEY ("PID_TIPO_PORTABILIDADE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_PORTABILIDADE" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ADD CONSTRAINT "TIPO_PRODUTO_FK" FOREIGN KEY ("PID_TIPO_PRODUTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_PRODUTO" ("CD_TIPO_PRODUTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ADD CONSTRAINT "TB_DOCUMENTO_PORTABILIDADE_FK1" FOREIGN KEY ("PID_DOCUMENTO_PORTABILIDADE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ("ID_DOCUMENTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ADD CONSTRAINT "TB_DOCUMENTO_PREVIDENCIA_FK2" FOREIGN KEY ("PID_DOCUMENTO_PREVIDENCIA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_PREVIDENCIA" ("PID_DOCUMENTO_PREVIDENCIA") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE_STATUS" ADD CONSTRAINT "TB_PORTABILIDADE_FK" FOREIGN KEY ("PID_PORTABILIDADE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_PORTABILIDADE" ("PID_DOCUMENTO_PORTABILIDADE") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_HISTORICO_DOCUMENTO" ADD CONSTRAINT "TB_HIST_DOC_SITUACAO_FK2" FOREIGN KEY ("PID_SITUACAO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_SITUACAO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_HISTORICO_DOCUMENTO" ADD CONSTRAINT "TB_HIST_DOC_SEG_DOC_FK1" FOREIGN KEY ("PID_DOCUMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ("ID_DOCUMENTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_HISTORICO_DOCUMENTO" ADD CONSTRAINT "TB_MOTIVO_RECUSA_FK" FOREIGN KEY ("PID_MOTIVO_RECUSA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_MOTIVO_RECUSA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_RESPONSAVEL_LEGAL" ADD CONSTRAINT "TB_RESP_LEGAL_CLIENTE_FK2" FOREIGN KEY ("PID_CLIENTE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_RESPONSAVEL_LEGAL" ADD CONSTRAINT "TB_RESPONSAVEL_LEGAL_FK1" FOREIGN KEY ("PID_DOCUMENTO_CIVIL")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_CIVIL" ("CD_DOCUMENTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_SEXO_FK10" FOREIGN KEY ("PID_SEXO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_SEXO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_TIUTLARIDADE_FK6" FOREIGN KEY ("PID_TITULARIDADE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TITULARIDADE" ("CD_TITULARIDADE") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_DOCUMENTO_FK7" FOREIGN KEY ("PID_DOCUMENTO_CIVIL")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_CIVIL" ("CD_DOCUMENTO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_ENDERECO_FK9" FOREIGN KEY ("PID_ENDERECO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_ESTADO_CIVIL_FK5" FOREIGN KEY ("PID_ESTADO_CIVIL")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_ESTADO_CIVIL" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_OCUPACAO_FK1" FOREIGN KEY ("PID_OCUPACAO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_OCUPACAO" ("CD_OCUPACAO") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_ORGAO_EMISSOR_FK8" FOREIGN KEY ("PID_ORGAO_EMISSOR")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_ORGAO_EMISSOR" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_NACIONALIDADE_FK2" FOREIGN KEY ("PID_PAIS_NACIONALIDADE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_PAIS" ("CD_PAIS") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_PAIS_OUTRA_NAC_FK3" FOREIGN KEY ("PID_PAIS_OUTRA_NACIONALIDADE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_PAIS" ("CD_PAIS") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ADD CONSTRAINT "TB_CLIENTE_PAIS_END_POSTAL_FK" FOREIGN KEY ("PID_PAIS_ENDERECO_POSTAL")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_PAIS" ("CD_PAIS") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_OBSERVACAO" ADD CONSTRAINT "TB_OBS_TB_INVESTIMENTO_FK" FOREIGN KEY ("PID_INVESTIMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_INVESTIMENTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_HISTORICO_DOC_CORRETOR" ADD CONSTRAINT "TB_HIST_DOC_TB_USUARIO_FK" FOREIGN KEY ("PID_USUARIO_ATUAL")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_HISTORICO_DOC_CORRETOR" ADD CONSTRAINT "TB_HIST_DOC_TB_USUARIO_FKV1" FOREIGN KEY ("PID_USUARIO_ANTERIOR")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_ESTRUTURA_VENDA" ADD CONSTRAINT "PID_EMPRESA" FOREIGN KEY ("PID_EMPRESA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PROPOSTA_FUNDO_INVESTIMENTO" ADD CONSTRAINT "TB_DOC_PREV_FK" FOREIGN KEY ("PID_DOCUMENTO_PREVIDENCIA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO_PREVIDENCIA" ("PID_DOCUMENTO_PREVIDENCIA") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PROPOSTA_FUNDO_INVESTIMENTO" ADD CONSTRAINT "TB_FUND_INVEST_FK" FOREIGN KEY ("PID_FUNDO_INVESTIMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_FUNDO_INVESTIMENTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO" ADD CONSTRAINT "CD_TIPO_ENDERECO_FK2" FOREIGN KEY ("PID_TIPO_ENDERECO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_ENDERECO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_ENDERECO" ADD CONSTRAINT "TB_PESSOA_ENDERECO__UF_FK3" FOREIGN KEY ("PID_UF")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_UF" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ADD CONSTRAINT "EMPRESA_FK1" FOREIGN KEY ("PID_EMPRESA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ADD CONSTRAINT "PERFIL_FK2" FOREIGN KEY ("PID_PERFIL")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_PERFIL" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ADD CONSTRAINT "TB_USUARIO_TB_EV_FK" FOREIGN KEY ("PID_ESTRUTURA_VENDA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_ESTRUTURA_VENDA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ADD CONSTRAINT "TB_USUARIO_TB_GRUPO_FK" FOREIGN KEY ("PID_GRUPO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_GRUPO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ADD CONSTRAINT "TB_USUARIO_TB_VISAO_FK" FOREIGN KEY ("PID_VISAO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_VISAO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_RISCO_PREFORMAT_COB" ADD CONSTRAINT "TB_COBERTURA_FK" FOREIGN KEY ("PID_COBERTURA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_COBERTURA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_RISCO_PREFORMAT_COB" ADD CONSTRAINT "TB_RISCO_PRE_FORMATADO_FK" FOREIGN KEY ("PID_RISCO_PRE_FORMATADO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_RISCO_PRE_FORMATADO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_GRUPO_FUNCIONALIDADE" ADD CONSTRAINT "PID_FUNC_FK" FOREIGN KEY ("PID_FUNCIONALIDADE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_FUNCIONALIDADE" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_GRUPO_FUNCIONALIDADE" ADD CONSTRAINT "PID_GRUPO_FK" FOREIGN KEY ("PID_GRUPO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_GRUPO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CODIGO_ACESSO" ADD CONSTRAINT "PID_COMPRA_FK1" FOREIGN KEY ("PID_COMPRA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_COMPRA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_INVESTIMENTO" ADD CONSTRAINT "TB_INVESTIMENTO_TB_EMPRESA_FK" FOREIGN KEY ("PID_EMPRESA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_INVESTIMENTO" ADD CONSTRAINT "TB_TIPO_RISCO_FK" FOREIGN KEY ("PID_TIPO_RISCO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_RISCO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_INVESTIMENTO" ADD CONSTRAINT "TB_INVEST_TB_RISC_PREFORMAT_FK" FOREIGN KEY ("PID_RISCO_PRE_FORMAT")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_RISCO_PRE_FORMATADO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_INVESTIMENTO" ADD CONSTRAINT "TB_INVEST_TB_TP_INVEST_FK" FOREIGN KEY ("PID_TIPO_INVESTIMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_INVESTIMENTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_INVESTIMENTO" ADD CONSTRAINT "TB_INVESTIMENTO_TB_PRODUTO_FK" FOREIGN KEY ("PID_PRODUTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_PRODUTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ADD CONSTRAINT "USUARIO_VISAOFK" FOREIGN KEY ("PID_USUARIO_B2C")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_USUARIO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_CANAL_VENDA" ADD CONSTRAINT "TB_CANAL_VENDA_FK1" FOREIGN KEY ("PID_EMPRESA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ADD CONSTRAINT "TB_DOCUMENTO_FK1" FOREIGN KEY ("PID_COMPRA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_COMPRA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ADD CONSTRAINT "TB_SEG_DOC_TIPO_FK5" FOREIGN KEY ("PID_TIPO_DOCUMENTO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_TIPO_DOCUMENTO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ADD CONSTRAINT "TB_SEG_CLIENTE_FK3" FOREIGN KEY ("PID_CLIENTE")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_CLIENTE" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ADD CONSTRAINT "TB_SEGURO_DOCUMENTO_FK1" FOREIGN KEY ("PID_EMPRESA")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_EMPRESA" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_DOCUMENTO" ADD CONSTRAINT "TB_SEG_RAMO_FK4" FOREIGN KEY ("PID_RAMO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_RAMO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_FUNDO_INVESTIMENTO" ADD CONSTRAINT "TB_FUNDO_INVEST_TB_FUNDO_FK" FOREIGN KEY ("PID_FUNDO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_FUNDO" ("ID") ENABLE;
ALTER TABLE "DB_EXCHANGE_VISAO_TST"."TB_PRODUTO" ADD CONSTRAINT "CD_RAMO" FOREIGN KEY ("PID_RAMO")
	  REFERENCES "DB_EXCHANGE_VISAO_TST"."TB_RAMO" ("ID") ENABLE;

prompt "Fim do Script CreateIndexConstr"

spool off

exit 